dataset_params:
  datasets: ['HDTF', 'VFHQ', '2.5D']
  audio: 'wav2vec2-base-960h'

model_params:
  dim: 256
  zdim: 256
  nhead: 8
  encoder_layers: 4
  decoder_layers: 8

diffusion_params:
  guidance: 2
  cond_drop_prob: 0.1

train_params:
  num_epochs: 4000
  lr: 1e-4
  min_lr: 1e-8
  batch_size: 256
  seq_n: 80
  pre_k: 10
  checkpoint_freq: 500
